### ISSUE TITLE
Enquiries about the attacks

### ISSUE THREAD

**Issue by BasselFouad** [ebagdasa/backdoors101#6]
Does the fact that the function synthesizes_inputs is not implemented mean that all of the attacks in the paper are still not implemented ? Or only batch poisoning ?

**Comment by DavidHidde** [comment]
Hi, since the author hasn't replied yet, I'll try to help.

Are you referring to `synthesizer.py` ?  It's meant as an abstract base class so it's not implemented on purpose. As far as I can tell, the pixel, complex and pattern syntehtisizers are implemented. The complex synthesizer needs some small modifications though to make it work.

**Comment by ebagdasa** [comment]
hey, sorry, yeah as @DavidHidde mentioned: look at the folder, they have all other synthesizers there. Let me know if anything needs to be fixed.
