### ISSUE TITLE
Problem saving results into "runs" and "saved_models" 

### ISSUE THREAD

**Issue by michaelTJC96** [ebagdasa/backdoors101#9]
Hi there,

As I am a beginner on Federated Learning and its backdoor attacks, may I check how do I view the training results on tensorboard? Nothing shows on the tensorboard.
![image](https://user-images.githubusercontent.com/53596227/124016888-ad824c80-da18-11eb-9e9d-a5b5d241bcc9.png)

Even when I aborted the training, it shows the error "Aborted training. No output generated". I have created the folders "runs" and "saved_models" as mentioned in the instructions.
![image](https://user-images.githubusercontent.com/53596227/124017024-cf7bcf00-da18-11eb-8c03-d5ce6c81e75e.png)

**Comment by DavidHidde** [comment]
It might be helpful to add some output logs, since these screenshots don't really help. I suspect that it might have to do with an incorrect working directory (IDEs might start execution from the Python root folder). Have you tried running straight from the root folder with a terminal?

Also, to reply to the question you asked me in the other issue: you can contact me via email (d.h.boerema@student.rug.nl). I don't know much about federated learning but might be able to help you with some other stuff concerning attacks and defences.

**Comment by michaelTJC96** [comment]
Hi @DavidHidde thanks so much for your contact and help! I will contact you soon! As mentioned by @ebagdasa, I will need to change the params in yaml file!
![image](https://user-images.githubusercontent.com/53596227/124386683-2120a400-dd0e-11eb-9422-6b3399088215.png)
